// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What an agent is doing, parsed from its output (`task_activity`).
 */
export type ActivityKind = "message" | "tool" | "result" | "error" | "output";
