// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ActivityKind } from "./ActivityKind";

export type ActivityDto = { kind: ActivityKind, text: string, };
