// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The user-configurable automatic-backup schedule. `interval` is one of
 * `"off"`, `"daily"`, `"weekly"`; `keep` is how many newest backups to retain.
 * Payload of `get_backup_schedule` / argument of `set_backup_schedule`.
 */
export type BackupScheduleDto = { interval: string, keep: number, };
