// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Response from an explicit, user-initiated update check (GAP-M8-02 / ADR-0005).
 */
export type CheckUpdateResultDto = { update_available: boolean, current_version: string, latest_version: string | null, release_notes: string | null, published_at: string | null, };
