// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskAgent } from "./TaskAgent";
import type { TaskEffort } from "./TaskEffort";

/**
 * Input of `continue_task`: send more work to a finished, failed, stopped, or
 * interrupted task in the same worktree.
 */
export type ContinueTaskRequest = { id: string, prompt: string, 
/**
 * Switch agents (a handoff). Omit to keep the current agent, which resumes
 * its own session when possible.
 */
agent?: TaskAgent, 
/**
 * Replace the stored model for this run. Omit to keep the task's model.
 */
model?: string, 
/**
 * Replace the stored effort for this run. Omit to keep the task's effort.
 */
effort?: TaskEffort, };
