// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskAgent } from "./TaskAgent";

/**
 * Input of `continue_task`: send more work to a finished, failed, stopped, or
 * interrupted task in the same worktree.
 */
export type ContinueTaskRequest = { id: string, prompt: string, 
/**
 * Switch agents (a handoff). Omit to keep the current agent, which resumes
 * its own session when possible.
 */
agent?: TaskAgent, };
