// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskAgent } from "./TaskAgent";
import type { TaskPermission } from "./TaskPermission";

/**
 * Input of `create_task`.
 */
export type CreateTaskRequest = { 
/**
 * Any path inside the target git repository.
 */
repo_path: string, title: string, prompt: string, agent: TaskAgent, 
/**
 * Defaults to `edits`.
 */
permission?: TaskPermission, };
