// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskAgent } from "./TaskAgent";
import type { TaskPermission } from "./TaskPermission";

/**
 * Input of `create_task`.
 */
export type CreateTaskRequest = { 
/**
 * Any path inside the target git repository.
 */
repo_path: string, title: string, prompt: string, agent: TaskAgent, 
/**
 * Defaults to `edits`.
 */
permission?: TaskPermission, 
/**
 * Repository-relative files or folders (ending in `/`) this task owns.
 * Other agents are told not to edit them, and commits touching them are
 * refused for other tasks unless forced.
 */
claims?: Array<string>, 
/**
 * Hand off to the other agent automatically if this one hits a usage
 * limit. Defaults to true.
 */
auto_handoff?: boolean, };
