// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry of the shared decision log (`list_decisions`), the orchestrator's
 * memory of what happened across tasks in a repository.
 */
export type DecisionDto = { at_ms: number, task_id: string, task_title: string, repo_path: string, 
/**
 * `created` | `continued` | `handoff` | `auto_handoff` | `committed` |
 * `merged` | `merge_conflict` | `stopped` | `discarded`.
 */
kind: string, detail: string, };
