// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An agent adapter and whether it was detected on this machine.
 * Payload of the `list_detected_agents` command.
 */
export type DetectedAgent = { 
/**
 * Stable adapter id, e.g. `claude-code` or `codex`.
 */
id: string, display_name: string, 
/**
 * An installation/root was found.
 */
installed: boolean, 
/**
 * Detected agent version, when known.
 */
version: string | null, 
/**
 * Sessions ingested for this agent so far.
 */
session_count: number, 
/**
 * Effective local folders Lore checks for this adapter.
 */
roots: Array<string>, 
/**
 * User-selected folders within `roots`; these may be removed in Settings.
 */
custom_roots: Array<string>, };
