// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry of a workspace directory listing (`list_workspace_dir`).
 */
export type DirEntryDto = { name: string, 
/**
 * Path relative to the workspace root, `/`-separated.
 */
rel_path: string, is_dir: boolean, };
