// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A file the session touched.
 */
export type FileEventDto = { path: string, 
/**
 * `edit` | `write` | `create` | `delete` | `move` | `read` | `patch`.
 */
change_kind: string, old_path: string | null, lines_added: number | null, lines_removed: number | null, 
/**
 * Provenance: `agent_patch` | `agent_tool_input` | `lore_capture`.
 */
source: string, 
/**
 * A byte-faithful recorded patch payload is stored and can be fetched.
 */
has_patch: boolean, };
