// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A read-only file view (`read_workspace_file`).
 */
export type FileContentDto = { rel_path: string, 
/**
 * UTF-8 text, or null for binary files.
 */
text: string | null, size: number, 
/**
 * Only the first part of a large file was returned.
 */
truncated: boolean, };
