// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A user-defined folder for organizing threads. Payload element of
 * `list_folders`. `session_count` is how many threads are filed in it.
 */
export type FolderSummary = { id: string, name: string, session_count: number, 
/**
 * User ordering key; the list is sorted by this then name.
 */
position: number, };
