// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Result of forgetting a session. Payload of `forget_session`.
 */
export type ForgetReport = { blobs_removed: number, 
/**
 * Original agent source paths Lore does not own and did not delete.
 */
source_paths: Array<string>, };
