// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One provenance-labeled git observation for the session's git rail. The UI
 * must keep `agent_recorded`, `agent_patch`, `lore_captured`, and
 * `lore_reverified` visually distinct and never collapse them into one
 * unlabeled "session-time" rail. Payload element of `get_git_snapshot`.
 */
export type GitObservationDto = { segment_id: string | null, 
/**
 * `agent_recorded` | `agent_patch` | `lore_captured` | `lore_reverified`.
 */
source: string, 
/**
 * Time claimed by the source event, when any.
 */
event_ts: number | null, 
/**
 * When Lore read/verified it.
 */
observed_at: number, 
/**
 * `exact_event` | `near_event` | `retrospective` | `current_only`.
 */
temporal_confidence: string, branch: string | null, commit_sha: string | null, 
/**
 * Credential-free normalized remote.
 */
remote_url_norm: string | null, is_dirty: boolean | null, 
/**
 * Re-verification result: the recorded commit still exists.
 */
commit_exists: boolean | null, };
