// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reactive event emitted over IPC when a background job fails.
 */
export type JobFailedEvent = { job_id: string, kind: string, error: string, };
