// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One task in a merge queue.
 */
export type MergeQueueItemDto = { task_id: string, title: string, 
/**
 * `pending` | `updating` | `testing` | `merging` | `merged` | `failed` |
 * `skipped` | `cancelled` | `interrupted`.
 */
status: string, detail: string | null, };
