// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Outcome of `merge_task`.
 */
export type MergeResultDto = { merged: boolean, 
/**
 * Branch of the primary checkout the task was merged into.
 */
into_branch: string, 
/**
 * Conflicting paths when the merge was aborted.
 */
conflicts: Array<string>, message: string, };
