// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MergeQueueItemDto } from "./MergeQueueItemDto";

/**
 * State of a repository's merge queue (`get_merge_queue`).
 */
export type MergeQueueDto = { repo_path: string, running: boolean, test_command: string | null, items: Array<MergeQueueItemDto>, };
