// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessagePartDto } from "./MessagePartDto";

/**
 * One message/turn with its ordered parts. Element of `SessionDetail.messages`.
 */
export type MessageDto = { id: string, seq: number, 
/**
 * `user` | `assistant` | `system` | `tool` | `meta`.
 */
role: string, 
/**
 * `message` | `summary` | `compaction` | `attachment` | `title` | `mode` |
 * `pr_link` | `other`.
 */
event_kind: string, is_sidechain: boolean, ts: number | null, model: string | null, parts: Array<MessagePartDto>, };
