// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MessageDto } from "./MessageDto";

/**
 * Paginated list of messages with a keyset cursor.
 */
export type MessagePage = { messages: Array<MessageDto>, next_cursor: string | null, };
