// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One ordered content block within a message. Opaque/encrypted blocks carry no
 * readable content (`text`/`content_json` are null) and are never rendered.
 */
export type MessagePartDto = { ordinal: number, 
/**
 * `text` | `thinking` | `tool_use` | `tool_result` | `attachment` |
 * `summary` | `opaque` | `other`.
 */
kind: string, text: string | null, 
/**
 * Structured block payload as JSON text, when not plain text.
 */
content_json: string | null, 
/**
 * False for opaque/encrypted and (by default) thinking blocks.
 */
searchable: boolean, };
