// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Per-repository settings Lore keeps (`get_repo_settings` / `set_repo_test_command`).
 */
export type RepoSettingsDto = { repo_path: string, 
/**
 * Shell command the merge queue runs in a task's worktree before merging,
 * e.g. `npm test`. None means merges are not gated on tests.
 */
test_command: string | null, };
