// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A repository grouping for the Repositories view. Payload element of
 * `list_repositories`.
 */
export type RepositorySummary = { id: string, display_name: string, 
/**
 * Identity confidence: `confirmed` | `high` | `medium` | `low`.
 */
identity_confidence: string, 
/**
 * Latest local path hint, when known (may be display-sensitive).
 */
primary_path: string | null, 
/**
 * The repository's checkout(s) are gone from disk.
 */
is_missing: boolean, session_count: number, worktree_count: number, };
