// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Final tally returned by the `rescan` command.
 */
export type RescanResult = { discovered: number, ingested: number, skipped: number, failed: number, enriched: number, };
