// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Final tally returned by the `rescan` command. Content-free counters.
 */
export type RescanResult = { 
/**
 * Number of candidate session files discovered across all roots.
 */
discovered: number, 
/**
 * Number of new or modified sessions successfully parsed and ingested.
 */
ingested: number, 
/**
 * Number of sessions skipped because they were unchanged since prior ingest.
 */
skipped: number, 
/**
 * Number of sessions that failed to parse or ingest cleanly.
 */
failed: number, 
/**
 * Number of segments enriched with Git evidence.
 */
enriched: number, };
