// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Content-free progress for a running scan. Payload of the `scan_progress`
 * event — counts only, never session content.
 */
export type ScanProgress = { discovered: number, ingested: number, skipped: number, failed: number, enriched: number, 
/**
 * The scan pass has finished.
 */
done: boolean, };
