// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One search result over the redacted projections. `snippet` contains
 * highlight markers (`\u{e000}`…`\u{e001}`) around matched terms; the raw text
 * is redacted, so a flagged secret never appears. Payload element of `search`.
 */
export type SearchHit = { session_id: string, 
/**
 * `message_part` | `file_event` | `session`.
 */
source_kind: string, source_id: string, field: string, 
/**
 * Redacted snippet with highlight markers around matches.
 */
snippet: string, 
/**
 * FTS5 BM25 score (more negative = better match).
 */
rank: number, title: string | null, agent_id: string, started_at: number | null, };
