// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SearchHit } from "./SearchHit";

/**
 * One page of search results plus an opaque keyset cursor. `next_cursor` is
 * `Some` only when a full page was returned (more results may follow); pass it
 * back verbatim as the `cursor` argument to fetch the next page. A cursor is
 * valid only for the identical query and sort order that produced it. Payload of `search_page`.
 */
export type SearchPage = { hits: Array<SearchHit>, next_cursor: string | null, };
