// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reactive event emitted over IPC when a secret finding is discovered during ingest.
 */
export type SecretFlaggedEvent = { session_id: string, rule: string, severity: string, };
