// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reactive event emitted over IPC when a session is ingested or updated.
 */
export type SessionIngestedEvent = { session_id: string, agent_id: string, title: string | null, parse_status: string, };
