// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileEventDto } from "./FileEventDto";
import type { MessageDto } from "./MessageDto";
import type { SegmentDto } from "./SegmentDto";
import type { SessionSummary } from "./SessionSummary";

/**
 * The full read of one session in context. Payload of `get_session`.
 */
export type SessionDetail = { summary: SessionSummary, segments: Array<SegmentDto>, messages: Array<MessageDto>, file_events: Array<FileEventDto>, };
