// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A one-line session for list views. Payload element of `list_sessions`.
 */
export type SessionSummary = { id: string, agent_id: string, title: string | null, 
/**
 * Epoch milliseconds.
 */
started_at: number | null, 
/**
 * Epoch milliseconds.
 */
ended_at: number | null, message_count: number, tool_call_count: number, primary_model: string | null, 
/**
 * `ok` | `partial` | `failed`.
 */
parse_status: string, };
