// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How much an agent may do without asking (ADR-0007). Lore never bypasses
 * permission prompts or sandboxes.
 */
export type TaskPermission = "edits" | "auto";
