// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Files a task shares with another unmerged task (overlap warning, step 3).
 */
export type TaskOverlapDto = { task_id: string, title: string, files: Array<string>, };
