// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Emitted when tasks change (state, new output, or an automatic handoff), so
 * the UI can refresh just those tasks instead of polling everything.
 */
export type TasksChangedEvent = { ids: Array<string>, };
