// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Lifecycle of an orchestrated task.
 */
export type TaskState = "running" | "finished" | "failed" | "stopped" | "interrupted";
