// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which coding-agent CLI runs an orchestrated task (ADR-0007).
 */
export type TaskAgent = "claude_code" | "codex";
