// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TaskAgent } from "./TaskAgent";
import type { TaskOverlapDto } from "./TaskOverlapDto";
import type { TaskPermission } from "./TaskPermission";
import type { TaskState } from "./TaskState";

/**
 * One orchestrated task with its live status. Payload element of `list_tasks`.
 */
export type TaskDto = { id: string, title: string, prompt: string, agent: TaskAgent, state: TaskState, 
/**
 * Repository top-level the worktree was created from.
 */
repo_path: string, 
/**
 * Lore-owned worktree the agent runs in.
 */
worktree_path: string, branch: string, 
/**
 * Commit the worktree branched from.
 */
base_commit: string, created_at_ms: number, exit_code: number | null, 
/**
 * Commits on the task branch since `base_commit`.
 */
commits_ahead: number, 
/**
 * Paths changed relative to `base_commit`, committed or not (capped).
 */
changed_files: Array<string>, 
/**
 * Most recent human-readable line from the agent's output, truncated.
 */
last_activity: string | null, permission?: TaskPermission, 
/**
 * How many times an agent has run in this worktree (1 + continuations).
 */
runs?: number, 
/**
 * Paths with uncommitted changes in the worktree.
 */
uncommitted_count?: number, 
/**
 * Something needs the user: e.g. usage limit reached or not logged in.
 */
attention?: string, 
/**
 * Other unmerged tasks in the same repository that changed the same files.
 */
overlaps?: Array<TaskOverlapDto>, 
/**
 * Branch currently checked out in the task's repository (the merge target).
 */
repo_branch?: string, 
/**
 * Set once the task branch was merged into the primary checkout.
 */
merged_into?: string, };
