// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How hard the model should try (Claude `--effort`, Codex `model_reasoning_effort`).
 * Omit to use the agent's own default.
 */
export type TaskEffort = "low" | "medium" | "high" | "extra_high" | "max";
