// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Cumulative token usage and estimated cost across the entire archive.
 */
export type TokenTotalsDto = { total_input_tokens: number, total_output_tokens: number, total_cache_tokens: number, est_cost_usd: number, };
